on:
  push:
    branches:
      - main

name: Deploy start

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
              
      - name: docker build  
        id: build-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO_NAME: api-test
        run: |
          docker build -t $DOCKERHUB_USERNAME/public:$REPO_NAME ./
          docker push $DOCKERHUB_USERNAME/public:$REPO_NAME
          
      - uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.K3S_KUBE_CONFIG }}
          REPO_NAME: api-test
        with:
          args: patch deployment -n $REPO_NAME $REPO_NAME --patch '{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"redeploy\":\"${{ github.sha }}\"}}}}}'
