on:
  push:
    branches:
      - main

name: Deploy start

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
              
      - name: Docker Build  
        id: build-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO_NAME: api-test
        run: |
          #sed -i 's/redis-server/127.0.0.1/' .env.example
          cp .env.example .env
          docker build -t $DOCKERHUB_USERNAME/public:$REPO_NAME ./
          docker push $DOCKERHUB_USERNAME/public:$REPO_NAME

      - name: gitops
        id: gitops
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo $SSH_KEY > ~/.ssh/id_rsa
          chmod 600  ~/.ssh/id_rsa
          git clone git@github.com:kotjiac/api-test-deploy.git
          cd api-test-deploy
          find ./ -name deployments.yaml

