on:
  push:
    branches:
      - main

name: Deploy start

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
              
      - name: Docker Build  
        id: build-image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO_NAME: api-test
        run: |
          ##sed -i 's/redis-server/127.0.0.1/' .env.example
          #cp .env.example .env
          #docker build -t $DOCKERHUB_USERNAME/public:$REPO_NAME ./
          #docker push $DOCKERHUB_USERNAME/public:$REPO_NAME

      - name: Set SSH KEY
        id: set-ssh-key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
        
      - name: gitops
        id: gitops
        run: |
          git clone git@github.com:kotjiac/api-test-deploy.git
          cd api-test-deploy
          sed -E "s/(image: kotjiac).*/\1\/public:api-test-${{ github.sha }}/" manifests/deployment.yaml
          git add manifests/deployment.yaml
          git config --global user.email "gitops@meuchapa.net"
          git config --global user.name "GitOps"
          git commit -m "gitops-auto"
          git push
